// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGpFLssZOmDIo2AMwwXyWwFPgZFzglZwI',
    appId: '1:790231778183:web:68345f7041d6f08388c922',
    messagingSenderId: '790231778183',
    projectId: 'chatappabc',
    authDomain: 'chatappabc.firebaseapp.com',
    storageBucket: 'chatappabc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGh-3C5Z4wLmiJ2jO_7uv5OhFrgxhzjPk',
    appId: '1:790231778183:android:74b2251a5011901688c922',
    messagingSenderId: '790231778183',
    projectId: 'chatappabc',
    storageBucket: 'chatappabc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6UxhH9Ap9sowX4A6q4oeT9cz0-tM6oFQ',
    appId: '1:790231778183:ios:24ae7b2c776dde5d88c922',
    messagingSenderId: '790231778183',
    projectId: 'chatappabc',
    storageBucket: 'chatappabc.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatAppSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6UxhH9Ap9sowX4A6q4oeT9cz0-tM6oFQ',
    appId: '1:790231778183:ios:24ae7b2c776dde5d88c922',
    messagingSenderId: '790231778183',
    projectId: 'chatappabc',
    storageBucket: 'chatappabc.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatAppSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGpFLssZOmDIo2AMwwXyWwFPgZFzglZwI',
    appId: '1:790231778183:web:8ed03be95693943688c922',
    messagingSenderId: '790231778183',
    projectId: 'chatappabc',
    authDomain: 'chatappabc.firebaseapp.com',
    storageBucket: 'chatappabc.firebasestorage.app',
  );
}
